Loading screen component
NKateryna/discord-project pull request #13
Opened 2023-01-21 18:11 UTC by NKateryna

2023-01-21 19:17 UTC, RuFi2k requested changes

2023-01-21 19:17 UTC, RuFi2k commented on src/routes/index.js
> +          />
We don't need to use a loading screen as part of the routing system. It is used when loading some data, so we need to rely on loading state but not on route path

2023-01-22 14:54 UTC, ruslan-filyk requested changes

2023-01-22 14:54 UTC, ruslan-filyk commented on src/routes/index.js
> +          <Route index element={<Login />} />
There shouldn't be any route, instead, we better should use Navigate component

2023-01-23 14:07 UTC, RuFi2k approved these changes

2023-01-23 14:07 UTC, merged